/*
    Exception handling:
	-------------------

	throw:
	------
      


class  ThrowDemo1
{
	public static void main(String[] args) 
	{
		System.out.println(10/0);
		
		Exception in thread "main" java.lang.ArithmeticException: / by zero
        at ThrowDemo1.main(ThrowDemo1.java:14)
	}
}

*/

class  ThrowDemo1 extends Exception  //CheckedException
{
	static ThrowDemo1  obj1;

	ThrowDemo1(String  message){
	        super(message);
	}

	public static void main(String[] args) 
	{
		obj1=new ThrowDemo1("This is our description !!!");
       
		try{

		throw obj1;
	
		}
		catch(ThrowDemo1  e){
		     e.printStackTrace();
		}
		
	}
}
